# Generated by Django 4.2.6 on 2023-11-04 04:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_lesson_owner_alter_lesson_course_payments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="url",
            field=models.URLField(
                blank=True, max_length=250, null=True, verbose_name="Ссылка"
            ),
        ),
    ]
